bank_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'bank_app'


urlpatterns = [
   path('', views.index, name='index'),
   path('home/', views.home, name='home'),
   path('accounts/', views.accounts, name='accounts'),
   path('transfer/', views.transfer, name='transfer'),
   path('loans/', views.loans, name='loans'),
   path('loan_details/', views.loan_details, name='loan_details'),
   path('loan_details/<int:transaction_id>/', views.loan_details, name='loan_details'),
   path('profile/', views.profile, name='profile'),
   path('staff/', views.staff, name='staff'),
   path('staffAccountView/', views.staffAccountView, name='staffAccountView'),
   path('staffCustomerView/', views.staffCustomerView, name='staffCustomerView'),
   path('staffNewCustomer', views.staffNewCustomer, name='staffNewCustomer'),
   path('staffNewAccount', views.staffNewAccount, name='staffNewAccount'),
   path('staffTransfers', views.staffTransfers, name='staffTransfers'),
   ]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bank_app.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('login_app.urls'))
]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

bank_app/models.py
from http.client import PROCESSING
from django.contrib.auth.models import User
from django.db import models, transaction
from django.db.models.query import QuerySet
from decimal import Decimal


class Store(models.Model):
   @classmethod
   @property
   def uid(cls):
      return cls.objects.create()

   def __str__(self):
      return f'{self.pk}'

class Account(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE)
   title = models.CharField(max_length=200)
   balance = models.DecimalField(max_digits=6, decimal_places=2, default=0)
   last_update = models.DateTimeField(auto_now_add=True, null=True)

   class Meta:
      get_latest_by = 'pk'

   @property
   def movements(self) -> QuerySet:
      return Ledger.objects.filter(account=self)

   @property
   def money(self) -> Decimal:
      return self.movements.aggregate(models.Sum('amount'))['amount__sum'] or Decimal(0)

   
   def __str__(self):
      return f"{self.pk} - {self.title} - {self.user} - {self.money}"

class Customer(models.Model):
   BASIC = 'basic'
   SILVER = 'silver'
   GOLD = 'GOLD'

   RANKS = [
      (BASIC, 'Basic'),
      (SILVER, 'Silver'),
      (GOLD, 'Gold'),
   ]

   user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
   phone_number = models.CharField(max_length=20)
   customer_rank = models.CharField(choices=RANKS, default=BASIC, max_length=6)

   @property
   def full_name(self) -> str:
      return f'{self.user.first_name} {self.user.last_name}'
   
   @property
   def accounts(self) -> QuerySet:
      return Account.objects.filter(user=self.user)

   
   def __str__(self):
      return f'{self.user} - {self.full_name} - {self.customer_rank}'

class Ledger(models.Model):
   account = models.ForeignKey(Account, on_delete=models.PROTECT)
   transaction = models.ForeignKey(Store, on_delete=models.PROTECT)
   amount = models.DecimalField(max_digits=10, decimal_places=2)
   text = models.TextField(default="text")

   @classmethod
   def transfer(cls, amount, debit_account, debit_text, credit_account, credit_text, is_loan=False):
      assert amount >= 0
      with transaction.atomic():
         if debit_account.money >= amount or is_loan:
            uid = Store.uid
            cls(amount=-amount, transaction=uid, account=debit_account, text=debit_text,).save()
            cls(amount=amount, transaction=uid, account=credit_account, text=credit_text).save()
         else:
            print("Sorry")
      return uid
   
   def __str__(self):
      return f'{self.amount} -- {self.transaction} -- {self.account} -- {self.text}'

bank_app/forms.py
from dataclasses import fields
from email.policy import default
from logging import PlaceHolder
from urllib import request
from django import forms
from django.contrib.auth.models import User
from .models import Account
from .models import Customer


class createCustomer(forms.ModelForm):
  class Meta:
    model = Customer
    fields = ('phone_number', 'customer_rank')

class UpdateCustomerForm(forms.ModelForm):
  class Meta:
    model = Customer
    fields = ('user', 'phone_number', 'customer_rank')

class createUser(forms.ModelForm):
  class Meta:
    model = User
    fields = ('first_name', 'last_name', 'username', 'email', 'password')

class UpdateUserForm(forms.ModelForm):
  username = forms.CharField(required=False)
  class Meta:
    model = User
    fields = ('first_name', 'last_name', 'username', 'email')

class createAccount(forms.ModelForm):
  class Meta:
    model = Account
    fields = ('title', 'user')
    # title = forms.CharField(max_length = 200)
    # user = forms.CharField(max_length=200)

class TransferForm(forms.Form):
  amount = forms.DecimalField(max_digits=10)
  debit_account = forms.ModelChoiceField(label='Debit Account', queryset=Customer.objects.none())
  debit_text = forms.CharField(max_length=35)
  credit_account = forms.IntegerField(label='Credit Account Number')
  credit_text = forms.CharField(max_length=35)

  def clean(self):
      super().clean()
      credit_account = self.cleaned_data.get('credit_account')
      Account.objects.get(pk=credit_account)
      return self.cleaned_data


class LoanForm(forms.Form):
  amount = forms.DecimalField(max_digits=10)
  period = forms.CharField()
  account = forms.ModelChoiceField(label='Choose account', queryset=Customer.objects.none())
  debit_text = forms.CharField(max_length=35)
  credit_text = forms.CharField(max_length=35)

  def clean(self):
    super().clean()
    return self.cleaned_data

class PaymentForm(forms.Form):
  amount = forms.DecimalField(max_digits=10)
  period = forms.CharField()
  customer_account = forms.ModelChoiceField(label='Choose account', queryset=Customer.objects.none())
  debit_text = forms.CharField(max_length=35)
  credit_text = forms.CharField(max_length=35)

  def clean(self):
    super().clean()
    return self.cleaned_data
# Not in use I THINK

class UserForm(forms.ModelForm):
    username = forms.CharField(label='Username', disabled=True)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

bank_app/views.py
from curses.ascii import FF
from multiprocessing import context
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .models import Account, Customer, Ledger
from django.contrib.auth.models import User
from .forms import createAccount, createCustomer, createUser, UpdateUserForm, UpdateCustomerForm, TransferForm, LoanForm
from decimal import Decimal


def index(request):
   return render(request, 'bank_app/index.html')


@login_required
def home(request):
   user = request.user
   if request.method == "POST":
      print("Hello")
      account_form = createAccount(request.POST)
      if account_form.is_valid():
         Account.objects.create(user=User.objects.get(pk=user.id), title=account_form.cleaned_data['title'])
   if request.user.is_staff:
      context = {
         'form': createAccount,
         'accounts': Account.objects.all(),
         'user_id': user.id,
         'customers': Customer.objects.all(),
      }
      return render(request, 'bank_app/staff.html', context)
   else:
      context = {
         'form': createAccount,
         'accounts': Account.objects.all(),
         'user_id': user.id,
         'customers': Customer.objects.all(),
      }
      return render(request, 'bank_app/home.html', context)

@login_required
def accounts(request):
   user=request.user
   context = {
      'accounts': Account.objects.all(),
      'user_id': user.id,
      'ledger': Ledger.objects.all()
      }
   return render(request, 'bank_app/accounts.html', context)

@login_required
def loans(request):
   user=request.user
   if request.method == "POST":
      loan_form = LoanForm(request.POST)
      loan_form.fields['account'].queryset = request.user.customer.accounts
      if loan_form.is_valid():
         amount = loan_form.cleaned_data['amount']
         account = Account.objects.get(pk=loan_form.cleaned_data['account'].pk)
         bank = Account.objects.get(pk=11) #The Bank
         debit_text = loan_form.cleaned_data['debit_text']
         credit_text = loan_form.cleaned_data['credit_text']
         is_loan = True
         transfer = Ledger.transfer(amount, bank, debit_text, account, credit_text, is_loan)
         print(transfer)
         return HttpResponseRedirect('/loans')
   else:
      loan_form = LoanForm()
      loan_form.fields['account'].queryset = request.user.customer.accounts
   context = {
      'user_id': user.id,
      'customers': Customer.objects.all(),
      'loan_form': loan_form,
      'accounts': Account.objects.all(),
      'ledger': Ledger.objects.all()
   }
   return render(request, 'bank_app/loans.html', context)

@login_required
def loan_details(request, transaction_id):
   transactions = Ledger.objects.filter(transaction_id=transaction_id)
   print(transactions)
   if request.method == "POST":
      loan_form = LoanForm(request.POST)
      loan_form.fields['account'].queryset = request.user.customer.accounts
      if loan_form.is_valid():
         amount = loan_form.cleaned_data['amount']
         customer_account = Account.objects.get(pk=loan_form.cleaned_data['account'].pk)
         account = Account.objects.get(pk=11) #The Bank
         debit_text = loan_form.cleaned_data['debit_text']
         credit_text = loan_form.cleaned_data['credit_text']
         transfer = Ledger.transfer(amount, customer_account, debit_text, account, credit_text)
         print(transfer)
   else:
      loan_form = LoanForm()
      loan_form.fields['account'].queryset = request.user.customer.accounts

   context = {
      'transactions':transactions,
      'accounts': Account.objects.all(),
      'loan_form': loan_form,

   }
   return render(request, 'bank_app/loan_details.html', context)

@login_required
def transfer(request):
   if request.method == "POST":
      transfer_form = TransferForm(request.POST)
      transfer_form.fields['debit_account'].queryset = request.user.customer.accounts
      if transfer_form.is_valid():
         debit_account = Account.objects.get(pk=transfer_form.cleaned_data['debit_account'].pk)
         debit_text = transfer_form.cleaned_data['debit_text']
         credit_account = Account.objects.get(pk=transfer_form.cleaned_data['credit_account'])
         credit_text = transfer_form.cleaned_data['credit_text']
         amount = transfer_form.cleaned_data['amount']
         transfer = Ledger.transfer(amount, debit_account, debit_text, credit_account, credit_text)
         print(transfer)
   else:
      transfer_form = TransferForm()
      transfer_form.fields['debit_account'].queryset = request.user.customer.accounts
      print(transfer_form.fields['debit_account'].queryset)

      # print(transfer_form.fields['debit_account'].queryset)
   context = {
      'transfer_form':transfer_form
   }
   return render(request, 'bank_app/transfer.html', context)

@login_required
def profile(request):
   user = request.user
   print(user)
   update_user_form = UpdateUserForm(instance=user)
   if request.method == "POST":
      update_user_form = UpdateUserForm(request.POST, instance=user)
      if update_user_form.is_valid:
         update_user_form.save()

   context = {
      'update_user_form': update_user_form,
      'user_id': user.id,
      'customers': Customer.objects.all()
   }
   return render(request, 'bank_app/profile.html', context)

# Admin

@login_required
def staff(request):
   assert request.user.is_staff, 'Not for regular customers, only for admin'
   context = {
         'customers': Customer.objects.all(),
      }
   return render(request, 'bank_app/staff.html', context)

@login_required
def staffCustomerView(request):
   user = request.user
   assert request.user.is_staff, 'Not for regular customers, only for admin'
   if request.method == "POST":
      update_customer_form = UpdateCustomerForm(request.POST, instance=request.user.customer)
      if update_customer_form.is_valid:
         update_customer_form.save()
   context = {
      'update_customer_form': UpdateCustomerForm,
      'user_id': user.id,
      'customers': Customer.objects.all(),
   }
   return render(request, 'bank_app/staffCustomerView.html', context)

@login_required
def staffAccountView(request):
   assert request.user.is_staff, 'Not for regular customers, only for admin'
   context = {
      'accounts': Account.objects.all(),
   }
   return render(request, 'bank_app/staffAccountView.html', context)
@login_required
def staffNewCustomer(request):
   assert request.user.is_staff, 'Not for regular customers, only for admin'
   if request.method == "POST":
      print("NEW CUSTOMER ALERT")
      customer_form = createCustomer(request.POST)
      user_form = createUser(request.POST)
      if user_form.is_valid() and customer_form.is_valid():
         username = user_form.cleaned_data['username']
         first_name = user_form.cleaned_data['first_name']
         last_name = user_form.cleaned_data['last_name']
         email = user_form.cleaned_data['email']
         password = user_form.cleaned_data['password']
         phone_number = customer_form.cleaned_data['phone_number']
         customer_rank = customer_form.cleaned_data['customer_rank']
         user = User.objects.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=password)
         print(f'Username: {username} - email: {email}')
         Customer.objects.create(user=user, phone_number=phone_number, customer_rank=customer_rank)
   context = {
      'customer_form': createCustomer,
      'user_form': createUser,
      'customers': Customer.objects.all(),
   }
   return render(request, 'bank_app/staffNewCustomer.html', context)

@login_required
def staffNewAccount(request):
   assert request.user.is_staff, 'Not for regular customers, only for admin'
   user=request.user
   if request.method == "POST":
      print("Hello")
      account_form = createAccount(request.POST)
      if account_form.is_valid():
         Account.objects.create(user=account_form.cleaned_data['user'], title=account_form.cleaned_data['title'])
         print(user)
   context = {
         'account_form': createAccount,
         'accounts': Account.objects.all(),
         'user_id': user.id,
         'customers': Customer.objects.all(),
      }
   return render(request, 'bank_app/staffNewAccount.html', context)

@login_required
def staffTransfers(request):
   assert request.user.is_staff, 'Not for regular customers, only for admin'
   transfer_form = TransferForm()
   # transfer_form.fields['debit_account'].queryset = request.user.customer.accounts
   print(request.user.customer.accounts)
   print(transfer_form.fields['debit_account'])
   if request.method == "POST":
      transfer_form = TransferForm(request.POST)
      if transfer_form.is_valid():
         debit_account = Account.objects.get(pk=transfer_form.cleaned_data['debit_account'])
         credit_account = Account.objects.get(pk=transfer_form.cleaned_data['credit_account'])
         amount = transfer_form.cleaned_data['amount']
         print(debit_account.pk)
         # print(credit_account)
         print(amount)
         transfer = Ledger.transfer(amount, debit_account, credit_account)
         print(transfer)
   else:
      transfer_form = TransferForm()
   context = {
      'transfer_form':TransferForm
   }

   return render(request, 'bank_app/staffTransfers.html', context)

bank_app/templates/bank_app/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name=“description” content=“base” />
    <meta name=“keywords” content=“bankingapp” />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>{% block title %} Sparion {% endblock %}</title>
  </head>
  <body class="blue">
    <nav>
      <ul class="ul">
        <li>
          <a href="{% url 'bank_app:index' %}" class="logo"></a>
        </li>
        <li>
          <a href="">Individuals</a>
        </li>
        <li>
          <a href="">Business</a>
        </li>
        <li>
          <a href="">Markets</a>
        </li>
        <li>
          <a href="">About Us</a>
        </li>
        <li>
          <a href="{% url 'login_app:login' %}">Sign in</a>
        </li>
      </ul>
    </nav>
    {% block content %}
    {% endblock %}
    <footer>
      <h5>footer</h5>
    </footer>
  </body>
</html>

bank_app/templates/bank_app/base/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name=“description” content=“base2” />
  <meta name=“keywords” content=“bank” />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'css/style2.css' %}" />
  <title>{% block title %} Sparion {% endblock %}</title>
</head>
<body class="white">
  <nav>
    <ul class="ul2">
      <li>
        <a href="{% url 'bank_app:index' %}" class="logo2"></a>
      </li>
      <li>
        <form action="{% url 'login_app:logout' %}">
          <button>Log out</button>
        </form>
      </li>
    </ul>
  </nav>
  <div class="staff_main">
    <ul class="staff_nav">
      <li>
        <a href="{% url 'bank_app:staff' %}">Dashboard</a>
      </li>
      <li>
        <a href="{% url 'bank_app:staffCustomerView' %}">
          Customers
        </a>
      </li>
      <li>
        <a href="{% url 'bank_app:staffAccountView' %}">
          Accounts
        </a>
      </li>
      <li>
        <a href="{% url 'bank_app:staffNewCustomer' %}">
          New customer
        </a>
      </li>
      <li>
        <a href="{% url 'bank_app:staffNewAccount' %}">
          New account
        </a>
      </li>
      <li>
        <a href="{% url 'bank_app:staffTransfers' %}">
          Transfers
        </a>
      </li>
    </ul>
    <div>
      <div>
      <h1 class="hello">Hello {{ user }}</h1>
      </div>
      {% block content %} {% endblock %}
    </div>
  </div>


<footer>
  <h5>footer</h5>
</footer>
</body>
</html>

bank_app/templates/bank_app/base/base3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name=“description” content=“base3” />
  <meta name=“keywords” content=“banking” />
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <link rel="stylesheet" href="{% static 'css/style2.css' %}"/>
  <title>{% block title %} Sparion {% endblock %}</title>
</head>
<body class="white">
  <nav>
    <ul class="ul2">
      <li>
        <a href="{% url 'bank_app:index' %}" class="logo2"></a>
      </li>
      <li>
        <form action="{% url 'login_app:logout' %}">
          <button>Log out</button>
        </form>
      </li>
    </ul>
  </nav>
  <div class="staff_main">
    <ul class="staff_nav">
      <li>
        <a href="{% url 'bank_app:home' %}">Dashboard</a>
      </li>
      <li>
        <a href="{% url 'bank_app:accounts' %}">
          My accounts
        </a>
      </li>
      <li>
        <a href="{% url 'bank_app:transfer' %}">
          Transfer
        </a>
      </li>
      <li>
        <a href="{% url 'bank_app:loans' %}">
          Loans
        </a>
      </li>
      <li>
        <a href="{% url 'bank_app:profile' %}">
          My profile
        </a>
      </li>
    </ul>
    <div>
      <div>
      <h1 class="hello">Hello {{ user.first_name }}</h1>
      </div>
      {% block content %} {% endblock %}
    </div>
  </div>
<footer>
  <h5>footer</h5>
</footer>
</body>
</html>