bank_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'bank_app'


urlpatterns = [
   path('', views.index, name='index'),
   path('home/', views.home, name='home'),
   path('accounts/', views.accounts, name='accounts'),
   path('transfer/', views.transfer, name='transfer'),
   path('loans/', views.loans, name='loans'),
   path('loan_details/', views.loan_details, name='loan_details'),
   path('loan_details/<int:transaction_id>/', views.loan_details, name='loan_details'),
   path('profile/', views.profile, name='profile'),
   path('staff/', views.staff, name='staff'),
   path('staffAccountView/', views.staffAccountView, name='staffAccountView'),
   path('staffCustomerView/', views.staffCustomerView, name='staffCustomerView'),
   path('staffNewCustomer', views.staffNewCustomer, name='staffNewCustomer'),
   path('staffNewAccount', views.staffNewAccount, name='staffNewAccount'),
   path('staffTransfers', views.staffTransfers, name='staffTransfers'),
   ]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bank_app.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('login_app.urls'))
]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

bank_app/models.py
from http.client import PROCESSING
from django.contrib.auth.models import User
from django.db import models, transaction
from django.db.models.query import QuerySet
from decimal import Decimal


class Store(models.Model):
   @classmethod
   @property
   def uid(cls):
      return cls.objects.create()

   def __str__(self):
      return f'{self.pk}'

class Account(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE)
   title = models.CharField(max_length=200)
   balance = models.DecimalField(max_digits=6, decimal_places=2, default=0)
   last_update = models.DateTimeField(auto_now_add=True, null=True)

   class Meta:
      get_latest_by = 'pk'

   @property
   def movements(self) -> QuerySet:
      return Ledger.objects.filter(account=self)

   @property
   def money(self) -> Decimal:
      return self.movements.aggregate(models.Sum('amount'))['amount__sum'] or Decimal(0)

   
   def __str__(self):
      return f"{self.pk} - {self.title} - {self.user} - {self.money}"

class Customer(models.Model):
   BASIC = 'basic'
   SILVER = 'silver'
   GOLD = 'GOLD'

   RANKS = [
      (BASIC, 'Basic'),
      (SILVER, 'Silver'),
      (GOLD, 'Gold'),
   ]

   user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
   phone_number = models.CharField(max_length=20)
   customer_rank = models.CharField(choices=RANKS, default=BASIC, max_length=6)

   @property
   def full_name(self) -> str:
      return f'{self.user.first_name} {self.user.last_name}'
   
   @property
   def accounts(self) -> QuerySet:
      return Account.objects.filter(user=self.user)

   
   def __str__(self):
      return f'{self.user} - {self.full_name} - {self.customer_rank}'

class Ledger(models.Model):
   account = models.ForeignKey(Account, on_delete=models.PROTECT)
   transaction = models.ForeignKey(Store, on_delete=models.PROTECT)
   amount = models.DecimalField(max_digits=10, decimal_places=2)
   text = models.TextField(default="text")

   @classmethod
   def transfer(cls, amount, debit_account, debit_text, credit_account, credit_text, is_loan=False):
      assert amount >= 0
      with transaction.atomic():
         if debit_account.money >= amount or is_loan:
            uid = Store.uid
            cls(amount=-amount, transaction=uid, account=debit_account, text=debit_text,).save()
            cls(amount=amount, transaction=uid, account=credit_account, text=credit_text).save()
         else:
            print("Sorry")
      return uid
   
   def __str__(self):
      return f'{self.amount} -- {self.transaction} -- {self.account} -- {self.text}'

bank_app/forms.py
from dataclasses import fields
from email.policy import default
from logging import PlaceHolder
from urllib import request
from django import forms
from django.contrib.auth.models import User
from .models import Account
from .models import Customer


class createCustomer(forms.ModelForm):
  class Meta:
    model = Customer
    fields = ('phone_number', 'customer_rank')

class UpdateCustomerForm(forms.ModelForm):
  class Meta:
    model = Customer
    fields = ('user', 'phone_number', 'customer_rank')

class createUser(forms.ModelForm):
  class Meta:
    model = User
    fields = ('first_name', 'last_name', 'username', 'email', 'password')

class UpdateUserForm(forms.ModelForm):
  username = forms.CharField(required=False)
  class Meta:
    model = User
    fields = ('first_name', 'last_name', 'username', 'email')

class createAccount(forms.ModelForm):
  class Meta:
    model = Account
    fields = ('title', 'user')
    # title = forms.CharField(max_length = 200)
    # user = forms.CharField(max_length=200)

class TransferForm(forms.Form):
  amount = forms.DecimalField(max_digits=10)
  debit_account = forms.ModelChoiceField(label='Debit Account', queryset=Customer.objects.none())
  debit_text = forms.CharField(max_length=35)
  credit_account = forms.IntegerField(label='Credit Account Number')
  credit_text = forms.CharField(max_length=35)

  def clean(self):
      super().clean()
      credit_account = self.cleaned_data.get('credit_account')
      Account.objects.get(pk=credit_account)
      return self.cleaned_data


class LoanForm(forms.Form):
  amount = forms.DecimalField(max_digits=10)
  period = forms.CharField()
  account = forms.ModelChoiceField(label='Choose account', queryset=Customer.objects.none())
  debit_text = forms.CharField(max_length=35)
  credit_text = forms.CharField(max_length=35)

  def clean(self):
    super().clean()
    return self.cleaned_data

class PaymentForm(forms.Form):
  amount = forms.DecimalField(max_digits=10)
  period = forms.CharField()
  customer_account = forms.ModelChoiceField(label='Choose account', queryset=Customer.objects.none())
  debit_text = forms.CharField(max_length=35)
  credit_text = forms.CharField(max_length=35)

  def clean(self):
    super().clean()
    return self.cleaned_data
# Not in use I THINK

class UserForm(forms.ModelForm):
    username = forms.CharField(label='Username', disabled=True)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

bank_app/views.py
from curses.ascii import FF
from multiprocessing import context
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .models import Account, Customer, Ledger
from django.contrib.auth.models import User
from .forms import createAccount, createCustomer, createUser, UpdateUserForm, UpdateCustomerForm, TransferForm, LoanForm
from decimal import Decimal


def index(request):
   return render(request, 'bank_app/index.html')


@login_required
def home(request):
   user = request.user
   if request.method == "POST":
      print("Hello")
      account_form = createAccount(request.POST)
      if account_form.is_valid():
         Account.objects.create(user=User.objects.get(pk=user.id), title=account_form.cleaned_data['title'])
   if request.user.is_staff:
      context = {
         'form': createAccount,
         'accounts': Account.objects.all(),
         'user_id': user.id,
         'customers': Customer.objects.all(),
      }
      return render(request, 'bank_app/staff.html', context)
   else:
      context = {
         'form': createAccount,
         'accounts': Account.objects.all(),
         'user_id': user.id,
         'customers': Customer.objects.all(),
      }
      return render(request, 'bank_app/home.html', context)

@login_required
def accounts(request):
   user=request.user
   context = {
      'accounts': Account.objects.all(),
      'user_id': user.id,
      'ledger': Ledger.objects.all()
      }
   return render(request, 'bank_app/accounts.html', context)

@login_required
def loans(request):
   user=request.user
   if request.method == "POST":
      loan_form = LoanForm(request.POST)
      loan_form.fields['account'].queryset = request.user.customer.accounts
      if loan_form.is_valid():
         amount = loan_form.cleaned_data['amount']
         account = Account.objects.get(pk=loan_form.cleaned_data['account'].pk)
         bank = Account.objects.get(pk=11) #The Bank
         debit_text = loan_form.cleaned_data['debit_text']
         credit_text = loan_form.cleaned_data['credit_text']
         is_loan = True
         transfer = Ledger.transfer(amount, bank, debit_text, account, credit_text, is_loan)
         print(transfer)
         return HttpResponseRedirect('/loans')
   else:
      loan_form = LoanForm()
      loan_form.fields['account'].queryset = request.user.customer.accounts
   context = {
      'user_id': user.id,
      'customers': Customer.objects.all(),
      'loan_form': loan_form,
      'accounts': Account.objects.all(),
      'ledger': Ledger.objects.all()
   }
   return render(request, 'bank_app/loans.html', context)

@login_required
def loan_details(request, transaction_id):
   transactions = Ledger.objects.filter(transaction_id=transaction_id)
   print(transactions)
   if request.method == "POST":
      loan_form = LoanForm(request.POST)
      loan_form.fields['account'].queryset = request.user.customer.accounts
      if loan_form.is_valid():
         amount = loan_form.cleaned_data['amount']
         customer_account = Account.objects.get(pk=loan_form.cleaned_data['account'].pk)
         account = Account.objects.get(pk=11) #The Bank
         debit_text = loan_form.cleaned_data['debit_text']
         credit_text = loan_form.cleaned_data['credit_text']
         transfer = Ledger.transfer(amount, customer_account, debit_text, account, credit_text)
         print(transfer)
   else:
      loan_form = LoanForm()
      loan_form.fields['account'].queryset = request.user.customer.accounts

   context = {
      'transactions':transactions,
      'accounts': Account.objects.all(),
      'loan_form': loan_form,

   }
   return render(request, 'bank_app/loan_details.html', context)

@login_required
def transfer(request):
   if request.method == "POST":
      transfer_form = TransferForm(request.POST)
      transfer_form.fields['debit_account'].queryset = request.user.customer.accounts
      if transfer_form.is_valid():
         debit_account = Account.objects.get(pk=transfer_form.cleaned_data['debit_account'].pk)
         debit_text = transfer_form.cleaned_data['debit_text']
         credit_account = Account.objects.get(pk=transfer_form.cleaned_data['credit_account'])
         credit_text = transfer_form.cleaned_data['credit_text']
         amount = transfer_form.cleaned_data['amount']
         transfer = Ledger.transfer(amount, debit_account, debit_text, credit_account, credit_text)
         print(transfer)
   else:
      transfer_form = TransferForm()
      transfer_form.fields['debit_account'].queryset = request.user.customer.accounts
      print(transfer_form.fields['debit_account'].queryset)

      # print(transfer_form.fields['debit_account'].queryset)
   context = {
      'transfer_form':transfer_form
   }
   return render(request, 'bank_app/transfer.html', context)

@login_required
def profile(request):
   user = request.user
   print(user)
   update_user_form = UpdateUserForm(instance=user)
   if request.method == "POST":
      update_user_form = UpdateUserForm(request.POST, instance=user)
      if update_user_form.is_valid:
         update_user_form.save()

   context = {
      'update_user_form': update_user_form,
      'user_id': user.id,
      'customers': Customer.objects.all()
   }
   return render(request, 'bank_app/profile.html', context)

# Admin

@login_required
def staff(request):
   assert request.user.is_staff, 'Not for regular customers, only for admin'
   context = {
         'customers': Customer.objects.all(),
      }
   return render(request, 'bank_app/staff.html', context)

@login_required
def staffCustomerView(request):
   user = request.user
   assert request.user.is_staff, 'Not for regular customers, only for admin'
   if request.method == "POST":
      update_customer_form = UpdateCustomerForm(request.POST, instance=request.user.customer)
      if update_customer_form.is_valid:
         update_customer_form.save()
   context = {
      'update_customer_form': UpdateCustomerForm,
      'user_id': user.id,
      'customers': Customer.objects.all(),
   }
   return render(request, 'bank_app/staffCustomerView.html', context)

@login_required
def staffAccountView(request):
   assert request.user.is_staff, 'Not for regular customers, only for admin'
   context = {
      'accounts': Account.objects.all(),
   }
   return render(request, 'bank_app/staffAccountView.html', context)
@login_required
def staffNewCustomer(request):
   assert request.user.is_staff, 'Not for regular customers, only for admin'
   if request.method == "POST":
      print("NEW CUSTOMER ALERT")
      customer_form = createCustomer(request.POST)
      user_form = createUser(request.POST)
      if user_form.is_valid() and customer_form.is_valid():
         username = user_form.cleaned_data['username']
         first_name = user_form.cleaned_data['first_name']
         last_name = user_form.cleaned_data['last_name']
         email = user_form.cleaned_data['email']
         password = user_form.cleaned_data['password']
         phone_number = customer_form.cleaned_data['phone_number']
         customer_rank = customer_form.cleaned_data['customer_rank']
         user = User.objects.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=password)
         print(f'Username: {username} - email: {email}')
         Customer.objects.create(user=user, phone_number=phone_number, customer_rank=customer_rank)
   context = {
      'customer_form': createCustomer,
      'user_form': createUser,
      'customers': Customer.objects.all(),
   }
   return render(request, 'bank_app/staffNewCustomer.html', context)

@login_required
def staffNewAccount(request):
   assert request.user.is_staff, 'Not for regular customers, only for admin'
   user=request.user
   if request.method == "POST":
      print("Hello")
      account_form = createAccount(request.POST)
      if account_form.is_valid():
         Account.objects.create(user=account_form.cleaned_data['user'], title=account_form.cleaned_data['title'])
         print(user)
   context = {
         'account_form': createAccount,
         'accounts': Account.objects.all(),
         'user_id': user.id,
         'customers': Customer.objects.all(),
      }
   return render(request, 'bank_app/staffNewAccount.html', context)

@login_required
def staffTransfers(request):
   assert request.user.is_staff, 'Not for regular customers, only for admin'
   transfer_form = TransferForm()
   # transfer_form.fields['debit_account'].queryset = request.user.customer.accounts
   print(request.user.customer.accounts)
   print(transfer_form.fields['debit_account'])
   if request.method == "POST":
      transfer_form = TransferForm(request.POST)
      if transfer_form.is_valid():
         debit_account = Account.objects.get(pk=transfer_form.cleaned_data['debit_account'])
         credit_account = Account.objects.get(pk=transfer_form.cleaned_data['credit_account'])
         amount = transfer_form.cleaned_data['amount']
         print(debit_account.pk)
         # print(credit_account)
         print(amount)
         transfer = Ledger.transfer(amount, debit_account, credit_account)
         print(transfer)
   else:
      transfer_form = TransferForm()
   context = {
      'transfer_form':TransferForm
   }

   return render(request, 'bank_app/staffTransfers.html', context)

bank_app/templates/bank_app/accounts.html
{% extends 'bank_app/base/base3.html' %}
{% block content %}
<h3>Your accounts</h3>
{% for account in accounts %}
  {% if account.user_id == user_id %}
  <li>{{ account.user }} - {{ account.title }} - {{ account.money }}kr</li>
    {% for transaction in account.movements %}
      <li>12.05.2022
      {% for movement in ledger %}
        {% if transaction.transaction_id == movement.transaction_id and movement.account_id != transaction.account_id %}
          {% for other_account in accounts %}
            {% if other_account.id == movement.account_id %}
              {{ other_account.title }}
              {% if other_account.title == 'BANK' %}
              LOAN
              {% endif %}
            {% endif %}
          {% endfor %}
        {% endif %}
      {% endfor %}
      {{ transaction.transaction_id }}
      {{ transaction.text }}
      {% if transaction.amount >= 0 %}
        {{ transaction.amount }}
      {% else %}
        {{ transaction.amount }}
      {% endif %}
      </li>
    {% endfor %}
  {% endif %}
{% endfor %}
{% endblock %}

bank_app/templates/bank_app/home.html
{% extends 'bank_app/base/base3.html' %} 
{% block content %}
  {% for customer in customers %}
    {% if customer.user_id == user_id %}
      <li>{{ customer.customer_rank }}</li>
    {% endif %}
  {% endfor %}
  {% for account in accounts %}
    {% if account.user_id == user_id %}
    <li>{{ account.user }} - {{ account.title }} - {{ account.balance }} - {{ account.money }}</li>
    {% endif %}
  {% endfor %}

  {% if error %}
    {{ error }}
  {% endif %} 
{% endblock %}

bank_app/templates/bank_app/index.html
{% extends 'bank_app/base/base.html' %} 
{% block content %}
   <div class="front">
      <div>
         <h1>Welcome to Sparion</h1>
         <p>
            Við hjálpum þér með það sem upp á vantar með Núláni í Arion appinu. Þú getur alltaf greitt inn á lánið, þér að kostnaðarlausu. 
         </p>
         <a href="{% url 'login_app:sign_up' %}">
            Let's start
         </a>
      </div>
   </div>
   <!-- <a href="{% url 'login_app:sign_up' %}">Sign Up</a>
   <a href="{% url 'login_app:login' %}">Login</a> -->
   {% endblock %}

bank_app/templates/bank_app/loan_details.html
{% extends 'bank_app/base/base3.html' %}
{% block content %}

<h1>Your loan details</h1>

{% for transaction in transactions %}
<li>{{transaction.amount}}</li>
<li>{{transaction.account.title}}</li>
{% endfor %}
<div class="form">
  <form action="" method="post">
    {% csrf_token %}
    {{ loan_form }}
    <input type="submit" value="Pay"/>
  </form>
</div>
{% endblock %}

bank_app/templates/bank_app/loans.html
{% extends 'bank_app/base/base3.html' %}
{% block content %}

{% if user.customer.customer_rank == 'basic' %}
<li>Sorry you can't take a loan</li>
<li>Contact customer service for further steps</li>
{% else %}
<!-- <div class="backmodall"></div> -->
<div class="modal" hidden>
  <div class="form">
    <form action="">
      <label for="amount">Amount</label>
      <input type="text" id="amount"/>
      <button>Pay</button>
    </form>
  </div>
</div>
<div class="flex">
  <div class="form" >
    <form action="" method="post">
      {% csrf_token %}
      {{ loan_form }}
      <input type="submit" value="Take loan"/>
    </form>
  </div>
  <div>
    <li>
      Lánsnúmer
      Lántakandi
      Útibú
      Tegund
      Gjalddagi
      Eftirstöðvar
    </li>
    {% for account in accounts %}
      {% if account.user_id == user_id %}
        {% for transaction in account.movements %}
          {% for movement in ledger %}
            {% if transaction.transaction_id == movement.transaction_id and movement.account_id != transaction.account_id %}
              {% for other_account in accounts %}
                {% if other_account.id == movement.account_id %}
                  {% if other_account.title == 'BANK' and transaction.amount >= 0 %}
                  <li>
                  <a href="{% url 'bank_app:loan_details' transaction.transaction_id %}">
                    {{ transaction.transaction_id }}
                    {{ user.customer.full_name}}
                    {{ transaction.amount }}
                  </a></li>
                  {% endif %}
                {% endif %}
              {% endfor %}
            {% endif %}
          {% endfor %}
        {% endfor %}
      {% endif %}
    {% endfor %}
  </div>
</div>
{% endif %}

{% endblock %}

bank_app/templates/bank_app/profile.html
{% extends 'bank_app/base/base3.html' %}
{% block content %}
My Profile
<div class="form">
<form action="" method="post">
  {% csrf_token %}
  {{ update_user_form}}
  <input type="submit" value="Update my profile"/>
</form>
</div>
<li>{{ user }}</li>
<li>{{ user.first_name }}</li>
<li>{{ user.last_name }}</li>
<li>{{ user.email }}</li>
{% for customer in customers %}
{% if customer.user_id == user_id %}
  <li>{{ customer.customer_rank }}</li>
  <li>{{ customer.phone_number }}</li>
{% endif %}
{% endfor %}
{% endblock %}

bank_app/templates/bank_app/staff.html
{% extends 'bank_app/base/base2.html' %} 
{% block content %}

{% endblock %}

bank_app/templates/bank_app/staffAccountView.html
{% extends 'bank_app/base/base2.html' %}
{% block content %}

  <h3>Active accounts</h3>
  {% for account in accounts %}
    <li>User: {{ account.user }}</li>
    <li>Account: {{ account.title }}</li>
    <li>Balance: {{ account.money }}</li>

    <br/>
  {% endfor %}
{% endblock %}

bank_app/templates/bank_app/staffCustomerView.html
{% extends 'bank_app/base/base2.html' %}
{% block content %}

<div class="flex">
  <div>
    <h3>Active customers</h3>
    {% for customer in customers %}
    <li>
      <a href="">{{ customer.full_name }}</a>
    </li>
    {% endfor %}
  </div>
  <div class="form">
    <form action="" method="post">
      {% csrf_token %}
      {{ update_customer_form }}
      <input type="submit" value="Update customer"/>
    </form>
  </div>
</div>
{% endblock %}

bank_app/templates/bank_app/staffNewAccount.html
{% extends 'bank_app/base/base2.html' %}
{% block content %}
  <h1>Create a new account</h1>
  <div class="form">
  <form action="" method="post">
    {% csrf_token %}
    {{account_form}}
    <input type="submit" value="Create an account" />
  </form>
</div>
{% endblock %}

bank_app/templates/bank_app/staffNewCustomer.html
{% extends 'bank_app/base/base2.html' %}
{% block content %}
  <h1>Create new customer</h1>
  <div class="form">
    <form action="" method="post">
      {% csrf_token %}
      {{user_form}}
      {{customer_form}}
      <input type="submit" value="Create a new cusomer" />
    </form>
  </div>
{% endblock %}

bank_app/templates/bank_app/staffTransfers.html
{% extends 'bank_app/base/base2.html' %}
{% block content %}
<div class="form">
  <form action="" method="post">
    {% csrf_token %}
    <fieldset>
      {% if account.user_id == user_id %}
      {{ transfer_form }}
      {% endif %}
    </fieldset>
    <input type="submit" value="Make transfer"/>
  </form>
</div>
{% endblock %}

bank_app/templates/bank_app/transfer.html
{% extends 'bank_app/base/base3.html' %}
{% block content %}
<div class="form">
  <form action="" method="post">
    {% csrf_token %}
      {% if account.user_id == user_id %}
      {{ transfer_form }}
      {% endif %}
    <input type="submit" value="Make transfer"/>
    <!-- <label for="amount">Send Amount</label>
    <input type="number" id="amount" placeholder="DKK 100,00">
    <label for="receiver">Receiver account</label>
    <input type="text" id="receiver" placeholder="Select account">
    <label for="sender">Sender account</label>
    <input type="text" id="sender" placeholder="Select account">
    <label for="delivery">Delivery type</label>
    <input type="text" id="delivery" placeholder="Select delivery type"> -->
  </form>
</div>
{% endblock %}